(function () {
	'use strict';

	window.airlines = [
		{ id: '*', code: '*', text: 'Múltiplas', country: '' },
		{ id: 'VX', code: 'VX', text: 'Aces Colombia', country: 'Colombia' },
		{ id: 'JP', code: 'JP', text: 'Adria Airways', country: 'Slovenia' },
		{ id: 'A3', code: 'A3', text: 'Aegean Airlines', country: 'Greece' },
		{ id: 'EI', code: 'EI', text: 'Aer Lingus', country: 'Ireland' },
		{ id: 'NG', code: 'NG', text: 'Aero Contractors', country: 'Nigeria' },
		{ id: 'P5', code: 'P5', text: 'Aero República', country: 'Colombia' },
		{ id: 'SU', code: 'SU', text: 'Aeroflot', country: 'Russian Federation' },
		{ id: 'AR', code: 'AR', text: 'Aerolineas Argentinas', country: 'Argentina' },
		{ id: '2K', code: '2K', text: 'Aerolineas Galapagos S.A. Aerogal', country: 'Ecuador' },
		{ id: 'VW', code: 'VW', text: 'Aeromar', country: 'Mexico' },
		{ id: 'AM', code: 'AM', text: 'Aeromexico', country: 'Mexico' },
		{ id: '8U', code: '8U', text: 'Afriqiyah Airways', country: 'Libya' },
		{ id: 'ZI', code: 'ZI', text: 'Aigle Azur', country: 'France' },
		{ id: 'AH', code: 'AH', text: 'Air Algérie', country: 'Algeria' },
		{ id: 'G9', code: 'G9', text: 'Air Arabia', country: 'United Arab Emirates' },
		{ id: 'KC', code: 'KC', text: 'Air Astana', country: 'Kazakhstan' },
		{ id: 'UU', code: 'UU', text: 'Air Austral', country: 'France' },
		{ id: 'BT', code: 'BT', text: 'Air Baltic', country: 'Latvia' },
		{ id: 'AB', code: 'AB', text: 'Air Berlin', country: 'Germany' },
		{ id: 'BP', code: 'BP', text: 'Air Botswana', country: 'Botswana' },
		{ id: 'SM', code: 'SM', text: 'Air Cairo', country: 'Egypt' },
		{ id: 'TY', code: 'TY', text: 'Air Caledonie', country: 'New Caledonia' },
		{ id: 'AC', code: 'AC', text: 'Air Canada', country: 'Canada' },
		{ id: 'TX', code: 'TX', text: 'Air Caraibes', country: 'French Caribbean' },
		{ id: 'CA', code: 'CA', text: 'Air China Limited', country: 'China' },
		{ id: 'XK', code: 'XK', text: 'Air Corsica', country: 'France' },
		{ id: 'UX', code: 'UX', text: 'Air Europa', country: 'Spain' },
		{ id: 'AF', code: 'AF', text: 'Air France', country: 'France' },
		{ id: 'GL', code: 'GL', text: 'Air Greenland', country: 'Greenland' },
		{ id: 'AI', code: 'AI', text: 'Air India', country: 'India' },
		{ id: 'JS', code: 'JS', text: 'Air Koryo', country: 'Korea' },
		{ id: 'NX', code: 'NX', text: 'Air Macau', country: 'Macao' },
		{ id: 'MD', code: 'MD', text: 'Air Madagascar', country: 'Madagascar' },
		{ id: 'KM', code: 'KM', text: 'Air Malta', country: 'Malta' },
		{ id: 'MK', code: 'MK', text: 'Air Mauritius', country: 'Mauritius' },
		{ id: '9U', code: '9U', text: 'Air Moldova', country: 'Moldova' },
		{ id: 'SW', code: 'SW', text: 'Air Namibia', country: 'Namibia' },
		{ id: 'NZ', code: 'NZ', text: 'Air New Zealand', country: 'New Zealand' },
		{ id: 'PX', code: 'PX', text: 'Air Niugini', country: 'Papua New Guinea' },
		{ id: 'YW', code: 'YW', text: 'Air Nostrum', country: 'Spain' },
		{ id: 'JU', code: 'JU', text: 'Air Serbia a.d. Beograd', country: 'Serbia' },
		{ id: 'HM', code: 'HM', text: 'Air Seychelles', country: 'Seychelles' },
		{ id: 'VT', code: 'VT', text: 'Air Tahiti', country: 'French Polynesia' },
		{ id: 'TN', code: 'TN', text: 'Air Tahiti Nui', country: 'French Polynesia' },
		{ id: 'TS', code: 'TS', text: 'Air Transat', country: 'Canada' },
		{ id: 'NF', code: 'NF', text: 'Air Vanuatu', country: 'Vanuatu' },
		{ id: 'SB', code: 'SB', text: 'Aircalin', country: 'New Caledonia' },
		{ id: '4Z', code: '4Z', text: 'Airlink', country: 'South Africa' },
		{ id: 'AS', code: 'AS', text: 'Alaska Airlines', country: 'United States' },
		{ id: 'AZ', code: 'AZ', text: 'Alitalia', country: 'Italy' },
		{ id: 'NH', code: 'NH', text: 'All Nippon Airways', country: 'Japan' },
		{ id: 'UJ', code: 'UJ', text: 'AlMasria Universal Airlines', country: 'Egypt' },
		{ id: 'K4', code: 'K4', text: 'ALS', country: 'Kenya' },
		{ id: 'AA', code: 'AA', text: 'American Airlines', country: 'United States' },
		{ id: 'W3', code: 'W3', text: 'Arik Air', country: 'Nigeria' },
		{ id: 'IZ', code: 'IZ', text: 'Arkia Israeli Airlines', country: 'Israel' },
		{ id: 'OZ', code: 'OZ', text: 'Asiana', country: 'Korea' },
		{ id: '5Y', code: '5Y', text: 'Atlas Air', country: 'United States' },
		{ id: 'KK', code: 'KK', text: 'Atlasjet Airlines', country: 'Turkey' },
		{ id: 'AU', code: 'AU', text: 'Austral', country: 'Argentina' },
		{ id: 'OS', code: 'OS', text: 'Austrian', country: 'Austria' },
		{ id: 'AV', code: 'AV', text: 'Avianca Colombia', country: 'Colombia' },
		{ id: 'O6', code: 'O6', text: 'Avianca', country: 'Brazil' },
		{ id: 'J2', code: 'J2', text: 'Azerbaijan Airlines', country: 'Azerbaijan' },
		{ id: 'AD', code: 'AD', text: 'Azul', country: 'Brazil' },
		{ id: 'JA*', code: 'JA*', text: 'B&H Airlines', country: 'Bosnia and Herzegovina' },
		{ id: 'UP', code: 'UP', text: 'Bahamasair', country: 'Bahamas' },
		{ id: 'PG', code: 'PG', text: 'Bangkok Air', country: 'Thailand' },
		{ id: 'JV', code: 'JV', text: 'Bearskin', country: 'Canada' },
		{ id: 'B2', code: 'B2', text: 'Belavia - Belarusian Airlines', country: 'Belarus' },
		{ id: '8H', code: '8H', text: 'BH AIR', country: 'Bulgaria' },
		{ id: 'BG', code: 'BG', text: 'Biman', country: 'Bangladesh' },
		{ id: 'NT', code: 'NT', text: 'Binter Canarias', country: 'Spain' },
		{ id: 'BV', code: 'BV', text: 'Blue Panorama', country: 'Italy' },
		{ id: 'KF', code: 'KF', text: 'Blue1', country: 'Finland' },
		{ id: 'BM', code: 'BM', text: 'bmi Regional', country: 'United Kingdom' },
		{ id: 'OB', code: 'OB', text: 'Boliviana de Aviación - BoA', country: 'Bolivia' },
		{ id: '4B', code: '4B', text: 'Boutique Air', country: 'United States' },
		{ id: '1X', code: '1X', text: 'Branson Airexpress', country: 'United States' },
		{ id: 'BA', code: 'BA', text: 'British Airways', country: 'United Kingdom' },
		{ id: 'SN', code: 'SN', text: 'Brussels Airlines', country: 'Belgium' },
		{ id: 'FB', code: 'FB', text: 'Bulgaria air', country: 'Bulgaria' },
		{ id: 'KX', code: 'KX', text: 'Cayman Airways', country: 'Cayman Islands' },
		{ id: 'BW', code: 'BW', text: 'Caribbean Airlines', country: 'Jamaica' },
		{ id: 'V3', code: 'V3', text: 'Carpatair', country: 'Romania' },
		{ id: 'CX', code: 'CX', text: 'Cathay Pacific', country: 'Hong Kong' },
		{ id: 'CI', code: 'CI', text: 'China Airlines', country: 'Chinese Taipei' },
		{ id: 'CK', code: 'CK', text: 'China Cargo Airlines', country: 'China' },
		{ id: 'MU', code: 'MU', text: 'China Eastern', country: 'China' },
		{ id: 'CF', code: 'CF', text: 'China Postal Airlines', country: 'China' },
		{ id: 'CZ', code: 'CZ', text: 'China Southern Airlines', country: 'China' },
		{ id: 'WX', code: 'WX', text: 'CityJet', country: 'Ireland' },
		{ id: 'MN', code: 'MN', text: 'Comair', country: 'South Africa' },
		{ id: 'DE', code: 'DE', text: 'Condor', country: 'Germany' },
		{ id: 'CM', code: 'CM', text: 'Copa Airlines', country: 'Panama' },
		{ id: 'XC', code: 'XC', text: 'Corendon Airlines', country: 'Turkey' },
		{ id: 'SS', code: 'SS', text: 'Corsair International', country: 'France' },
		{ id: 'CY', code: 'CY', text: 'Cyprus Airways', country: 'Cyprus' },
		{ id: 'OU', code: 'OU', text: 'Croatia Airlines', country: 'Croatia' },
		{ id: 'CU', code: 'CU', text: 'Cubana', country: 'Cuba' },
		{ id: 'OK', code: 'OK', text: 'Czech Airlines', country: 'Czech Republic' },
		{ id: 'DL', code: 'DL', text: 'Delta Air Lines', country: 'United States' },
		{ id: 'D0', code: 'D0', text: 'DHL Air', country: 'United Kingdom' },
		{ id: 'ES*', code: 'ES*', text: 'DHL Aviation EEMEA B.S.C.(c)', country: 'Bahrain' },
		{ id: 'Z6*', code: 'Z6*', text: 'Dniproavia', country: 'Ukraine' },
		{ id: 'D9', code: 'D9', text: 'Donavia', country: 'Russian Federation' },
		{ id: 'KA', code: 'KA', text: 'Dragonair', country: 'Hong Kong' },
		{ id: 'MS', code: 'MS', text: 'Egyptair', country: 'Egypt' },
		{ id: 'LY', code: 'LY', text: 'EL AL', country: 'Israel' },
		{ id: 'EK', code: 'EK', text: 'Emirates', country: 'United Arab Emirates' },
		{ id: 'OV', code: 'OV', text: 'Estonian Air', country: 'Estonia' },
		{ id: 'ET', code: 'ET', text: 'Ethiopian Airlines', country: 'Ethiopia' },
		{ id: 'EY', code: 'EY', text: 'Etihad Airways', country: 'United Arab Emirates' },
		{ id: 'F7', code: 'F7', text: 'Etihad Regional', country: 'Switzerland' },
		{ id: 'YU', code: 'YU', text: 'Euroatlantic Airways', country: 'Portugal' },
		{ id: 'QY', code: 'QY', text: 'European Air Transport', country: 'Germany' },
		{ id: 'EW', code: 'EW', text: 'Eurowings', country: 'Germany' },
		{ id: 'BR', code: 'BR', text: 'EVA Air', country: 'Chinese Taipei' },
		{ id: 'FX', code: 'FX', text: 'Federal Express', country: 'United States' },
		{ id: 'FJ', code: 'FJ', text: 'Fiji Airways', country: 'Fiji' },
		{ id: 'AY', code: 'AY', text: 'Finnair', country: 'Finland' },
		{ id: '7F', code: '7F', text: 'First Air', country: 'Canada' },
		{ id: 'BE', code: 'BE', text: 'flybe', country: 'United Kingdom' },
		{ id: 'FZ', code: 'FZ', text: 'Flydubai', country: 'United Arab Emirates' },
		{ id: 'FH', code: 'FH', text: 'Freebird Airlines', country: 'Turkey' },
		{ id: 'F9', code: 'F9', text: 'Frontier Airlines', country: 'United States' },
		{ id: 'GA', code: 'GA', text: 'Garuda', country: 'Indonesia' },
		{ id: 'A9', code: 'A9', text: 'Georgian Airways', country: 'Georgia' },
		{ id: 'ST', code: 'ST', text: 'Germania', country: 'Germany' },
		{ id: '4U', code: '4U', text: 'Germanwings', country: 'Germany' },
		{ id: 'G3', code: 'G3', text: 'Gol', country: 'Brazil' },
		{ id: 'ZK', code: 'ZK', text: 'Great Lakes Airlines', country: 'United States' },
		{ id: 'GF', code: 'GF', text: 'Gulf Air', country: 'Bahrain' },
		{ id: 'HR*', code: 'HR*', text: 'Hahn Air', country: 'Germany' },
		{ id: 'HU', code: 'HU', text: 'Hainan Airlines', country: 'China' },
		{ id: 'HA', code: 'HA', text: 'Hawaiian Airlines', country: 'United States' },
		{ id: 'YO', code: 'YO', text: 'Heli Air Monaco', country: 'Monaco' },
		{ id: '5K', code: '5K', text: 'Hi Fly', country: 'Portugal' },
		{ id: 'HX', code: 'HX', text: 'Hong Kong Airlines', country: 'Hong Kong' },
		{ id: 'UO', code: 'UO', text: 'Hong Kong Express Airways', country: 'Hong Kong' },
		{ id: 'IB', code: 'IB', text: 'Iberia', country: 'Spain' },
		{ id: 'FI', code: 'FI', text: 'Icelandair', country: 'Iceland' },
		{ id: '7I', code: '7I', text: 'Insel Air', country: 'Curaçao' },
		{ id: 'D6', code: 'D6', text: 'Interair', country: 'South Africa' },
		{ id: '4O', code: '4O', text: 'Interjet', country: 'Mexico' },
		{ id: '3L', code: '3L', text: 'InterSky', country: 'Austria' },
		{ id: 'IR', code: 'IR', text: 'Iran Air', country: 'Iran' },
		{ id: 'EP', code: 'EP', text: 'Iran Aseman Airlines', country: 'Iran' },
		{ id: 'WP', code: 'WP', text: 'Island Air', country: 'United States' },
		{ id: '6H', code: '6H', text: 'Israir', country: 'Israel' },
		{ id: 'JL', code: 'JL', text: 'Japan Airlines', country: 'Japan' },
		{ id: 'J9', code: 'J9', text: 'Jazeera Airways', country: 'Kuwait' },
		{ id: '9W', code: '9W', text: 'Jet Airways', country: 'India' },
		{ id: 'S2', code: 'S2', text: 'Jet Lite Limited', country: 'India' },
		{ id: 'B6', code: 'B6', text: 'JetBlue', country: 'United States' },
		{ id: 'R5', code: 'R5', text: 'Jordan Aviation', country: 'Jordan' },
		{ id: '5N', code: '5N', text: 'Jsc Nordavia-RA', country: 'Russian Federation' },
		{ id: 'HO', code: 'HO', text: 'Juneyao Airlines', country: 'China' },
		{ id: 'KQ', code: 'KQ', text: 'Kenya Airways', country: 'Kenya' },
		{ id: 'M5', code: 'M5', text: 'Kenmore Air', country: 'United States' },
		{ id: 'Y9', code: 'Y9', text: 'Kish Air', country: 'Iran' },
		{ id: 'KL', code: 'KL', text: 'KLM', country: 'Netherlands' },
		{ id: 'KE', code: 'KE', text: 'Korean Air', country: 'Korea' },
		{ id: 'KU', code: 'KU', text: 'Kuwait Airways', country: 'Kuwait' },
		{ id: 'LR', code: 'LR', text: 'Lacsa', country: 'Costa Rica' },
		{ id: 'TM', code: 'TM', text: 'Lam', country: 'Mozambique' },
		{ id: 'LA', code: 'LA', text: 'Lan Airlines', country: 'Chile' },
		{ id: '4M', code: '4M', text: 'Lan Argentina', country: 'Argentina' },
		{ id: 'LP', code: 'LP', text: 'Lan Perú', country: 'Peru' },
		{ id: 'XL', code: 'XL', text: 'LanEcuador', country: 'Ecuador' },
		{ id: 'LI', code: 'LI', text: 'LIAT Airlines', country: 'Antigua and Barbuda' },
		{ id: 'N4', code: 'N4', text: 'LLC "NORD WIND"', country: 'Russian Federation' },
		{ id: 'LO', code: 'LO', text: 'LOT Polish Airlines', country: 'Poland' },
		{ id: 'LH', code: 'LH', text: 'Lufthansa', country: 'Germany' },
		{ id: 'CL', code: 'CL', text: 'Lufthansa CityLine', country: 'Germany' },
		{ id: 'LG', code: 'LG', text: 'Luxair', country: 'Luxembourg' },
		{ id: 'W5', code: 'W5', text: 'Mahan Air', country: 'Iran' },
		{ id: 'MH', code: 'MH', text: 'Malaysia Airlines', country: 'Malaysia' },
		{ id: 'TF', code: 'TF', text: 'Malmö Aviation', country: 'Sweden' },
		{ id: 'AE', code: 'AE', text: 'Mandarin Airlines', country: 'Chinese Taipei' },
		{ id: 'M7', code: 'M7', text: 'MAS AIR', country: 'Mexico' },
		{ id: 'ME', code: 'ME', text: 'MEA', country: 'Lebanon' },
		{ id: 'IG', code: 'IG', text: 'Meridiana fly', country: 'Italy' },
		{ id: 'YV', code: 'YV', text: 'Mesa Airlines', country: 'United States' },
		{ id: 'OM', code: 'OM', text: 'MIAT', country: 'Mongolia' },
		{ id: 'YM', code: 'YM', text: 'Montenegro Airlines', country: 'Montenegro' },
		{ id: 'NE', code: 'NE', text: 'Nesma Airlines', country: 'Egypt' },
		{ id: 'HG', code: 'HG', text: 'NIKI', country: 'Austria' },
		{ id: 'NP', code: 'NP', text: 'Nile Air', country: 'Egypt' },
		{ id: 'KZ', code: 'KZ', text: 'Nippon Cargo Airlines (NCA)', country: 'Japan' },
		{ id: 'BJ', code: 'BJ', text: 'Nouvelair', country: 'Tunisia' },
		{ id: 'OA', code: 'OA', text: 'Olympic Air', country: 'Greece' },
		{ id: 'WY', code: 'WY', text: 'Oman Air', country: 'Oman' },
		{ id: '8Q', code: '8Q', text: 'Onur Air', country: 'Turkey' },
		{ id: 'EC', code: 'EC', text: 'OpenSkies', country: 'United Kingdom' },
		{ id: 'R2', code: 'R2', text: 'Orenair', country: 'Russian Federation' },
		{ id: 'LW', code: 'LW', text: 'Pacific Wings', country: 'United States' },
		{ id: 'P3', code: 'P3', text: 'Passaredo', country: 'Brazil' },
		{ id: 'PC', code: 'PC', text: 'Pegasus Airlines', country: 'Turkey' },
		{ id: 'NI', code: 'NI', text: 'PGA-Portugália Airlines', country: 'Portugal' },
		{ id: 'PR', code: 'PR', text: 'Philippine Airlines', country: 'Philippines' },
		{ id: 'PK', code: 'PK', text: 'PIA', country: 'Pakistan' },
		{ id: 'PD', code: 'PD', text: 'Porter Airlines', country: 'Canada' },
		{ id: 'PW', code: 'PW', text: 'Precision Air', country: 'Tanzania' },
		{ id: 'PV', code: 'PV', text: 'PrivatAir', country: 'Switzerland' },
		{ id: 'QF', code: 'QF', text: 'Qantas', country: 'Australia' },
		{ id: 'QR', code: 'QR', text: 'Qatar Airways', country: 'Qatar' },
		{ id: 'FV', code: 'FV', text: 'Rossiya Airlines', country: 'Russian Federation' },
		{ id: 'AT', code: 'AT', text: 'Royal Air Maroc', country: 'Morocco' },
		{ id: 'BI', code: 'BI', text: 'Royal Brunei', country: 'Brunei Darussalam' },
		{ id: 'RJ', code: 'RJ', text: 'Royal Jordanian', country: 'Jordan' },
		{ id: 'WB', code: 'WB', text: 'RwandAir', country: 'Rwanda' },
		{ id: 'S7', code: 'S7', text: 'S7 Airlines', country: 'Russian Federation' },
		{ id: 'SA', code: 'SA', text: 'SAA', country: 'South Africa' },
		{ id: 'FA*', code: 'FA*', text: 'Safair', country: 'South Africa' },
		{ id: '4Q', code: '4Q', text: 'Safi Airways', country: 'Afghanistan' },
		{ id: 'S3', code: 'S3', text: 'Santa Barbara', country: 'Venezuela' },
		{ id: 'SK', code: 'SK', text: 'SAS', country: 'Sweden' },
		{ id: 'SP', code: 'SP', text: 'Sata Air Açores', country: 'Portugal' },
		{ id: 'S4', code: 'S4', text: 'Sata Internacional', country: 'Portugal' },
		{ id: 'SV', code: 'SV', text: 'Saudi Arabian Airlines', country: 'Saudi Arabia' },
		{ id: 'BB', code: 'BB', text: 'Seaborne Airlines', country: 'Puerto Rico' },
		{ id: 'K5', code: 'K5', text: 'SeaPort Airlines', country: 'United States' },
		{ id: 'SC', code: 'SC', text: 'Shandong Airlines', country: 'China' },
		{ id: 'FM', code: 'FM', text: 'Shanghai Airlines', country: 'China' },
		{ id: 'ZH', code: 'ZH', text: 'Shenzhen Airlines', country: 'China' },
		{ id: 'SQ', code: 'SQ', text: 'Sia', country: 'Singapore' },
		{ id: '3U', code: '3U', text: 'Sichuan Airlines', country: 'China' },
		{ id: 'MI', code: 'MI', text: 'Silkair', country: 'Singapore' },
		{ id: '3M', code: '3M', text: 'Silver Airways', country: 'United States' },
		{ id: 'H2', code: 'H2', text: 'Sky Airline', country: 'Chile' },
		{ id: 'XZ', code: 'XZ', text: 'South African Express Airways', country: 'South Africa' },
		{ id: 'NK', code: 'NK', text: 'Spirit Airlines', country: 'United States' },
		{ id: 'UL', code: 'UL', text: 'SriLankan', country: 'Sri Lanka' },
		{ id: 'SD', code: 'SD', text: 'Sudan Airways', country: 'Sudan' },
		{ id: 'XQ*', code: 'XQ*', text: 'SunExpress', country: 'Turkey' },
		{ id: 'PY', code: 'PY', text: 'Surinam Airways', country: 'Suriname' },
		{ id: 'LX', code: 'LX', text: 'SWISS', country: 'Switzerland' },
		{ id: 'RB', code: 'RB', text: 'Syrianair', country: 'Syrian Arab Republic' },
		{ id: 'SY', code: 'SY', text: 'Sun Country Airlines', country: 'United States' },
		{ id: 'DT', code: 'DT', text: 'TAAG - Angola Airlines', country: 'Angola' },
		{ id: 'TA', code: 'TA', text: 'Taca', country: 'El Salvador' },
		{ id: 'T0', code: 'T0', text: 'Taca Peru', country: 'Peru' },
		{ id: 'VR', code: 'VR', text: 'Tacv Cabo Verde Airlines', country: 'Cape Verde' },
		{ id: 'PZ', code: 'PZ', text: 'Tam - Transportes Aéreos del Mercosur Sociedad Anónima', country: 'Paraguay' },
		{ id: 'JJ', code: 'JJ', text: 'Tam', country: 'Brazil' },
		{ id: 'EQ', code: 'EQ', text: 'Tame - Linea Aérea del Ecuador', country: 'Ecuador' },
		{ id: 'TP', code: 'TP', text: 'Tap', country: 'Portugal' },
		{ id: 'RO', code: 'RO', text: 'Tarom', country: 'Romania' },
		{ id: 'SF', code: 'SF', text: 'Tassili Airlines', country: 'Algeria' },
		{ id: 'TG', code: 'TG', text: 'Thai Airways International', country: 'Thailand' },
		{ id: 'TK', code: 'TK', text: 'Thy - Turkish Airlines', country: 'Turkey' },
		{ id: 'GS', code: 'GS', text: 'Tianjin Airlines', country: 'China' },
		{ id: '3V', code: '3V', text: 'TNT Airways S.A.', country: 'Belgium' },
		{ id: 'UN', code: 'UN', text: 'Transaero', country: 'Russian Federation' },
		{ id: 'GE', code: 'GE', text: 'TransAsia Airways', country: 'Chinese Taipei' },
		{ id: 'X3*', code: 'X3*', text: 'TUIfly', country: 'Germany' },
		{ id: 'TU', code: 'TU', text: 'Tunisair', country: 'Tunisia' },
		{ id: 'PS', code: 'PS', text: 'Ukraine International Airlines', country: 'Ukraine' },
		{ id: 'UA', code: 'UA', text: 'United Airlines', country: 'United States' },
		{ id: '5X', code: '5X', text: 'UPS Airlines', country: 'United States' },
		{ id: 'U6', code: 'U6', text: 'Ural Airlines', country: 'Russian Federation' },
		{ id: 'US', code: 'US', text: 'US Airways', country: 'United States' },
		{ id: 'QU', code: 'QU', text: 'UTair Ukraine', country: 'Ukraine' },
		{ id: 'UT', code: 'UT', text: 'UTair', country: 'Russian Federation' },
		{ id: 'HY', code: 'HY', text: 'Uzbekistan Airways', country: 'Uzbekistan' },
		{ id: 'VN', code: 'VN', text: 'Vietnam Airlines', country: 'Vietnam' },
		{ id: 'VS', code: 'VS', text: 'Virgin Atlantic', country: 'United Kingdom' },
		{ id: 'VA', code: 'VA', text: 'Virgin Australia', country: 'Australia' },
		{ id: 'VG', code: 'VG', text: 'Vlm Airlines', country: 'Belgium' },
		{ id: 'Y4*', code: 'Y4*', text: 'Volaris', country: 'Mexico' },
		{ id: 'VI*', code: 'VI*', text: 'Volga-Dnepr Airlines', country: 'Russian Federation' },
		{ id: 'VY', code: 'VY', text: 'Vueling', country: 'Spain' },
		{ id: 'WS', code: 'WS', text: 'WestJet', country: 'Canada' },
		{ id: 'WI', code: 'WI', text: 'White coloured by you', country: 'Portugal' },
		{ id: 'WF', code: 'WF', text: 'Wideroe', country: 'Norway' },
		{ id: 'MF', code: 'MF', text: 'Xiamen Airlines', country: 'China' },
		{ id: 'SE', code: 'SE', text: 'XL Airways France', country: 'France' },
		{ id: 'IY', code: 'IY', text: 'Yemenia', country: 'Yemen' },
	];

	window.airlinesByCode = {};
	window.airlinesByName = {};

	for (var i = 0; i < window.airlines.length; i++) {
		var airline = window.airlines[i];

		window.airlinesByCode[airline.code] = airline;
		window.airlinesByName[airline.text] = airline;
	}
})();
